# Current Version: 1.0.0

name: Build & Release hezhijie0327/NanoKVM-USB-CFWorkers

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Build NanoKVM-USB-CFWorkers
              run: |
                  git clone --depth 1 -b "dev" "https://github.com/sipeed/NanoKVM-USB" "/tmp/NanoKVM-USB"
                  rm -rf /tmp/NanoKVM-USB/browser/pnpm-*.yaml
                  cp -rf /tmp/NanoKVM-USB/browser/ ./
            - name: Step 3 - Release NanoKVM-USB-CFWorkers
              run: |
                  curl -s "https://raw.githubusercontent.com/hezhijie0327/Toolkit/main/Git.sh" > "/tmp/Git.sh"
                  sudo bash "/tmp/Git.sh" -u "hezhijie0327" -e "hezhijie0327@hotmail.com" -f "." -r "CNIPDb" -i "Synced by GitHub Actions" -m "push"
